In [130]:
!pip install pandas
!pip install tensorflow
!pip install sklearn
!pip install matplotlib


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'


  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [15 lines of output]
  The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
  rather than 'sklearn' for pip commands.
  
  Here is how to fix this error in the main use cases:
  - use 'pip install scikit-learn' rather than 'pip install sklearn'
  - replace 'sklearn' by 'scikit-learn' in your pip requirements files
    (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
  - if the 'sklearn' package is used by one of your dependencies,
    it would be great if you take some time to track which package uses
    'sklearn' instead of 'scikit-learn' and report it to their issue tracker
  - as a last resort, set the environment variable
    SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
  
  More information is available at
  https://github.com/scikit-learn/sklearn-pypi-package
  [end of output]
  
  note: This error originates from a subpr


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


# Preprocessing

In [131]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

# Load the dataset

In [132]:
incidents_data = pd.read_csv('datasets/root_cause_analysis.csv')
incidents_data.head()

ID  CPU_LOAD  MEMORY_LEAK_LOAD  DELAY  ERROR_1000  ERROR_1001  ERROR_1002  \
0   1         0                 0      0           0           1           0   
1   2         0                 0      0           0           0           0   
2   3         0                 1      1           0           0           1   
3   4         0                 1      0           1           1           0   
4   5         1                 1      0           1           0           1   

   ERROR_1003     ROOT_CAUSE  
0           1    MEMORY_LEAK  
1           1    MEMORY_LEAK  
2           1    MEMORY_LEAK  
3           1    MEMORY_LEAK  
4           0  NETWORK_DELAY

# Prepare Input Data for Deep Learning

In [133]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
incidents_data['ROOT_CAUSE'] = label_encoder.fit_transform(incidents_data['ROOT_CAUSE'])

incidents_data.head()

ID  CPU_LOAD  MEMORY_LEAK_LOAD  DELAY  ERROR_1000  ERROR_1001  ERROR_1002  \
0   1         0                 0      0           0           1           0   
1   2         0                 0      0           0           0           0   
2   3         0                 1      1           0           0           1   
3   4         0                 1      0           1           1           0   
4   5         1                 1      0           1           0           1   

   ERROR_1003  ROOT_CAUSE  
0           1           1  
1           1           1  
2           1           1  
3           1           1  
4           0           2

In [134]:
np_incidents = incidents_data.to_numpy().astype(float)
np_incidents

array([[   1.,    0.,    0., ...,    0.,    1.,    1.],
       [   2.,    0.,    0., ...,    0.,    1.,    1.],
       [   3.,    0.,    1., ...,    1.,    1.,    1.],
       ...,
       [ 998.,    1.,    1., ...,    0.,    0.,    1.],
       [ 999.,    0.,    1., ...,    0.,    0.,    2.],
       [1000.,    1.,    0., ...,    1.,    0.,    0.]])

In [135]:
X_data = np_incidents[:,1:-1]

In [136]:
X_data

array([[0., 0., 0., ..., 1., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 1., ..., 0., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 1., 0.]])

In [137]:
Y_data = np_incidents[:, -1]

In [138]:
Y_data

array([1., 1., 1., 1., 2., 2., 2., 0., 1., 2., 1., 0., 1., 0., 2., 1., 1.,
       1., 2., 1., 2., 1., 1., 1., 2., 1., 1., 2., 2., 1., 0., 1., 1., 2.,
       1., 0., 1., 0., 0., 2., 2., 0., 1., 0., 2., 2., 2., 0., 2., 0., 1.,
       0., 0., 0., 2., 1., 2., 1., 0., 0., 2., 1., 0., 1., 2., 1., 0., 0.,
       1., 2., 1., 0., 1., 0., 2., 1., 2., 2., 2., 2., 2., 1., 2., 1., 2.,
       2., 0., 1., 1., 0., 1., 1., 1., 1., 1., 2., 0., 1., 1., 1., 1., 1.,
       2., 0., 1., 2., 2., 0., 0., 1., 2., 2., 2., 0., 0., 0., 1., 1., 1.,
       2., 1., 0., 2., 0., 0., 2., 2., 2., 1., 0., 2., 1., 0., 0., 0., 0.,
       0., 2., 1., 1., 2., 0., 0., 1., 0., 2., 1., 2., 0., 2., 2., 1., 0.,
       2., 0., 0., 0., 2., 2., 1., 2., 2., 2., 0., 2., 2., 1., 0., 1., 1.,
       0., 1., 2., 1., 1., 0., 1., 1., 1., 0., 2., 1., 0., 0., 1., 0., 1.,
       2., 0., 1., 1., 1., 2., 1., 2., 0., 0., 0., 0., 1., 0., 2., 1., 1.,
       0., 2., 0., 1., 1., 0., 0., 0., 2., 0., 0., 0., 1., 2., 0., 1., 0.,
       0., 2., 1., 2., 2.

In [139]:
scaler = StandardScaler().fit(X_data)
X_data = scaler.transform(X_data)

In [140]:
X_data

array([[-0.94548368, -0.84747452, -0.80632811, ...,  1.03046381,
        -0.87210285,  1.27462619],
       [-0.94548368, -0.84747452, -0.80632811, ..., -0.97043679,
        -0.87210285,  1.27462619],
       [-0.94548368,  1.17997648,  1.24018993, ..., -0.97043679,
         1.14665375,  1.27462619],
       ...,
       [ 1.05765971,  1.17997648,  1.24018993, ..., -0.97043679,
        -0.87210285, -0.78454374],
       [-0.94548368,  1.17997648,  1.24018993, ...,  1.03046381,
        -0.87210285, -0.78454374],
       [ 1.05765971, -0.84747452, -0.80632811, ...,  1.03046381,
         1.14665375, -0.78454374]])

In [141]:
NB_CLASSES = len(np.unique(Y_data))
NB_FEATURES = X_data.shape[1]
print(NB_CLASSES, NB_FEATURES)

3 7


In [142]:
Y_data = tf.keras.utils.to_categorical(Y_data,NB_CLASSES)

In [143]:
Y_data

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [144]:
#Split training and test data
X_train,X_test,Y_train,Y_test = train_test_split( X_data, Y_data, test_size=0.10)

In [145]:
print(X_train.shape, Y_train.shape, X_test.shape, Y_test.shape)

(900, 7) (900, 3) (100, 7) (100, 3)


In [146]:
from tensorflow import keras
from tensorflow.keras import optimizers
from tensorflow.keras.regularizers import l2

EPOCHS = 20
BATCH_SIZE = 64
VERBOSE = 1

OUTPUT_CLASSES = len(label_encoder.classes_)
N_HIDDEN = 128
VALIDATION_SPLIT = 0.2

#Create a Keras sequential model
model = tf.keras.models.Sequential()

# Add a Dense Layer
model.add(keras.layers.Dense(N_HIDDEN, input_shape=(NB_FEATURES,), name='Dense-Layer-1', activation='relu'))

# Add a second Dense Layer
model.add(keras.layers.Dense(N_HIDDEN, name='Dense-Layer-2', activation='relu'))

# Add a softmax layer for categorical prediction
model.add(keras.layers.Dense(OUTPUT_CLASSES, name='Final', activation='softmax'))

# Compile the model
model.compile(
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Dense-Layer-1 (Dense)       (None, 128)               1024      
                                                                 
 Dense-Layer-2 (Dense)       (None, 128)               16512     
                                                                 
 Final (Dense)               (None, 3)                 387       
                                                                 
Total params: 17923 (70.01 KB)
Trainable params: 17923 (70.01 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [147]:
#Build the model
model.fit(X_train,
          Y_train,
          batch_size=BATCH_SIZE,
          epochs=EPOCHS,
          verbose=VERBOSE,
          validation_split=VALIDATION_SPLIT)


#Evaluate the model against the test dataset and print results
print("\nEvaluation against Test Dataset :\n------------------------------------")
model.evaluate(X_test,Y_test)

Epoch 1/20
12/12 [==============================] - 0s 10ms/step - loss: 0.8045 - accuracy: 0.7222 - val_loss: 0.5960 - val_accuracy: 0.8000
Epoch 2/20
12/12 [==============================] - 0s 3ms/step - loss: 0.5206 - accuracy: 0.8139 - val_loss: 0.5134 - val_accuracy: 0.8222
Epoch 3/20
12/12 [==============================] - 0s 3ms/step - loss: 0.4678 - accuracy: 0.8222 - val_loss: 0.4679 - val_accuracy: 0.8278
Epoch 4/20
12/12 [==============================] - 0s 3ms/step - loss: 0.4408 - accuracy: 0.8417 - val_loss: 0.4507 - val_accuracy: 0.8333
Epoch 5/20
12/12 [==============================] - 0s 3ms/step - loss: 0.4225 - accuracy: 0.8444 - val_loss: 0.4332 - val_accuracy: 0.8333
Epoch 6/20
12/12 [==============================] - 0s 3ms/step - loss: 0.4111 - accuracy: 0.8444 - val_loss: 0.4351 - val_accuracy: 0.8389
Epoch 7/20
12/12 [==============================] - 0s 3ms/step - loss: 0.4014 - accuracy: 0.8500 - val_loss: 0.4083 - val_accuracy: 0.8389
Epoch 8/20
12/12 [=

[0.4116809368133545, 0.8700000047683716]

# PREDICT

In [148]:
#Pass individual flags to Predict the root cause
import numpy as np

CPU_LOAD=1
MEMORY_LOAD=0
DELAY=0
ERROR_1000=0
ERROR_1001=1
ERROR_1002=1
ERROR_1003=0

prediction=np.argmax(model.predict(
    [[CPU_LOAD,MEMORY_LOAD,DELAY,
      ERROR_1000,ERROR_1001,ERROR_1002,ERROR_1003]]), axis=1 )

print(label_encoder.inverse_transform(prediction))

1/1 [==============================] - 0s 388ms/step
['DATABASE_ISSUE']


In [149]:
#Predicting as a Batch
print(label_encoder.inverse_transform(np.argmax(
    model.predict([[1,0,0,0,1,1,0],
                   [0,1,1,1,0,0,0],
                   [1,1,0,1,1,0,1],
                   [0,0,0,0,0,1,0],
                   [1,0,1,0,1,1,1]]), axis=1 )))

1/1 [==============================] - 0s 39ms/step
['DATABASE_ISSUE' 'NETWORK_DELAY' 'MEMORY_LEAK' 'DATABASE_ISSUE'
 'DATABASE_ISSUE']
